//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkflowSampleSystem.BLL
{
    
    
    public partial class WorkflowSampleSystemBLLContext : Framework.DomainDriven.BLL.Security.SecurityBLLBaseContext<WorkflowSampleSystem.Domain.PersistentDomainObjectBase, System.Guid, WorkflowSampleSystem.BLL.IWorkflowSampleSystemBLLFactoryContainer>, Framework.DomainDriven.BLL.IBLLFactoryContainerContext<Framework.DomainDriven.BLL.IBLLFactoryContainer<Framework.DomainDriven.BLL.Security.IDefaultSecurityBLLFactory<WorkflowSampleSystem.Domain.PersistentDomainObjectBase, System.Guid>>>, WorkflowSampleSystem.BLL.IWorkflowSampleSystemBLLContext
    {
        
        Framework.DomainDriven.BLL.IBLLFactoryContainer<Framework.DomainDriven.BLL.IDefaultBLLFactory<WorkflowSampleSystem.Domain.PersistentDomainObjectBase, System.Guid>> Framework.DomainDriven.BLL.IBLLFactoryContainerContext<Framework.DomainDriven.BLL.IBLLFactoryContainer<Framework.DomainDriven.BLL.IDefaultBLLFactory<WorkflowSampleSystem.Domain.PersistentDomainObjectBase, System.Guid>>>.Logics
        {
            get
            {
                return this.Logics;
            }
        }
        
        Framework.DomainDriven.BLL.IBLLFactoryContainer<Framework.DomainDriven.BLL.Security.IDefaultSecurityBLLFactory<WorkflowSampleSystem.Domain.PersistentDomainObjectBase, System.Guid>> Framework.DomainDriven.BLL.IBLLFactoryContainerContext<Framework.DomainDriven.BLL.IBLLFactoryContainer<Framework.DomainDriven.BLL.Security.IDefaultSecurityBLLFactory<WorkflowSampleSystem.Domain.PersistentDomainObjectBase, System.Guid>>>.Logics
        {
            get
            {
                return this.Logics;
            }
        }
    }
    
    public partial interface IWorkflowSampleSystemBLLContext : Framework.DomainDriven.BLL.Security.IAccessDeniedExceptionServiceContainer, Framework.DomainDriven.BLL.Security.ISecurityServiceContainer<Framework.DomainDriven.BLL.Security.IRootSecurityService<WorkflowSampleSystem.Domain.PersistentDomainObjectBase>>, Framework.DomainDriven.BLL.IBLLFactoryContainerContext<WorkflowSampleSystem.BLL.IWorkflowSampleSystemBLLFactoryContainer>, Framework.DomainDriven.IFetchServiceContainer<WorkflowSampleSystem.Domain.PersistentDomainObjectBase, Framework.DomainDriven.FetchBuildRule>
    {
        
        new WorkflowSampleSystem.BLL.IWorkflowSampleSystemBLLFactoryContainer Logics
        {
            get;
        }
    }
    
    public partial class SecurityDomainBLLBase<TDomainObject, TOperation> : Framework.DomainDriven.BLL.Security.DefaultSecurityDomainBLLBase<WorkflowSampleSystem.BLL.IWorkflowSampleSystemBLLContext, WorkflowSampleSystem.Domain.PersistentDomainObjectBase, TDomainObject, System.Guid, TOperation>
        where TDomainObject : WorkflowSampleSystem.Domain.PersistentDomainObjectBase
        where TOperation :  struct, System.Enum
    {
        
        public SecurityDomainBLLBase(WorkflowSampleSystem.BLL.IWorkflowSampleSystemBLLContext context, nuSpec.Abstraction.ISpecificationEvaluator specificationEvaluator = null) : 
                base(context, specificationEvaluator)
        {
        }
        
        public SecurityDomainBLLBase(WorkflowSampleSystem.BLL.IWorkflowSampleSystemBLLContext context, Framework.SecuritySystem.ISecurityProvider<TDomainObject> securityProvider, nuSpec.Abstraction.ISpecificationEvaluator specificationEvaluator = null) : 
                base(context, securityProvider, specificationEvaluator)
        {
        }
    }
    
    public partial class SecurityDomainBLLBase<TDomainObject> : WorkflowSampleSystem.BLL.SecurityDomainBLLBase<TDomainObject, Framework.DomainDriven.BLL.BLLBaseOperation>
        where TDomainObject : WorkflowSampleSystem.Domain.PersistentDomainObjectBase
    {
        
        public SecurityDomainBLLBase(WorkflowSampleSystem.BLL.IWorkflowSampleSystemBLLContext context) : 
                base(context)
        {
        }
        
        public SecurityDomainBLLBase(WorkflowSampleSystem.BLL.IWorkflowSampleSystemBLLContext context, Framework.SecuritySystem.ISecurityProvider<TDomainObject> securityProvider) : 
                base(context, securityProvider)
        {
        }
    }
    
    public partial interface IWorkflowSampleSystemBLLFactoryContainer : Framework.DomainDriven.BLL.IBLLFactoryContainer<Framework.DomainDriven.BLL.Security.IDefaultSecurityBLLFactory<WorkflowSampleSystem.Domain.PersistentDomainObjectBase, System.Guid>>
    {
        
        WorkflowSampleSystem.BLL.IBusinessUnitBLL BusinessUnit
        {
            get;
        }
        
        WorkflowSampleSystem.BLL.IBusinessUnitBLLFactory BusinessUnitFactory
        {
            get;
        }
        
        WorkflowSampleSystem.BLL.IEmployeeBLL Employee
        {
            get;
        }
        
        WorkflowSampleSystem.BLL.IEmployeeBLLFactory EmployeeFactory
        {
            get;
        }
        
        WorkflowSampleSystem.BLL.IHRDepartmentBLL HRDepartment
        {
            get;
        }
        
        WorkflowSampleSystem.BLL.IHRDepartmentBLLFactory HRDepartmentFactory
        {
            get;
        }
        
        WorkflowSampleSystem.BLL.ILocationBLL Location
        {
            get;
        }
        
        WorkflowSampleSystem.BLL.ILocationBLLFactory LocationFactory
        {
            get;
        }
        
        WorkflowSampleSystem.BLL.INamedLockBLL NamedLock
        {
            get;
        }
        
        WorkflowSampleSystem.BLL.INamedLockBLLFactory NamedLockFactory
        {
            get;
        }
    }
    
    public partial interface IBusinessUnitBLL : Framework.DomainDriven.BLL.Security.IDefaultSecurityDomainBLLBase<WorkflowSampleSystem.BLL.IWorkflowSampleSystemBLLContext, WorkflowSampleSystem.Domain.PersistentDomainObjectBase, WorkflowSampleSystem.Domain.BusinessUnit, System.Guid>
    {
    }
    
    public partial interface IBusinessUnitBLLFactory : Framework.DomainDriven.BLL.Security.ISecurityBLLFactory<WorkflowSampleSystem.BLL.IBusinessUnitBLL, WorkflowSampleSystem.Domain.BusinessUnit>
    {
    }
    
    public partial interface IEmployeeBLL : Framework.DomainDriven.BLL.Security.IDefaultSecurityDomainBLLBase<WorkflowSampleSystem.BLL.IWorkflowSampleSystemBLLContext, WorkflowSampleSystem.Domain.PersistentDomainObjectBase, WorkflowSampleSystem.Domain.Employee, System.Guid>
    {
    }
    
    public partial interface IEmployeeBLLFactory : Framework.DomainDriven.BLL.Security.ISecurityBLLFactory<WorkflowSampleSystem.BLL.IEmployeeBLL, WorkflowSampleSystem.Domain.Employee>
    {
    }
    
    public partial interface IHRDepartmentBLL : Framework.DomainDriven.BLL.Security.IDefaultSecurityDomainBLLBase<WorkflowSampleSystem.BLL.IWorkflowSampleSystemBLLContext, WorkflowSampleSystem.Domain.PersistentDomainObjectBase, WorkflowSampleSystem.Domain.HRDepartment, System.Guid>
    {
    }
    
    public partial interface IHRDepartmentBLLFactory : Framework.DomainDriven.BLL.Security.ISecurityBLLFactory<WorkflowSampleSystem.BLL.IHRDepartmentBLL, WorkflowSampleSystem.Domain.HRDepartment>
    {
    }
    
    public partial interface ILocationBLL : Framework.DomainDriven.BLL.Security.IDefaultSecurityDomainBLLBase<WorkflowSampleSystem.BLL.IWorkflowSampleSystemBLLContext, WorkflowSampleSystem.Domain.PersistentDomainObjectBase, WorkflowSampleSystem.Domain.Location, System.Guid>
    {
    }
    
    public partial interface ILocationBLLFactory : Framework.DomainDriven.BLL.Security.ISecurityBLLFactory<WorkflowSampleSystem.BLL.ILocationBLL, WorkflowSampleSystem.Domain.Location>
    {
    }
    
    public partial interface INamedLockBLL : Framework.DomainDriven.BLL.Security.IDefaultSecurityDomainBLLBase<WorkflowSampleSystem.BLL.IWorkflowSampleSystemBLLContext, WorkflowSampleSystem.Domain.PersistentDomainObjectBase, WorkflowSampleSystem.Domain.NamedLock, System.Guid>
    {
    }
    
    public partial interface INamedLockBLLFactory : Framework.DomainDriven.BLL.Security.ISecurityBLLFactory<WorkflowSampleSystem.BLL.INamedLockBLL, WorkflowSampleSystem.Domain.NamedLock>
    {
    }
}
